#
# Github Action to setup the audit-testsuite
#
# Copyright (c) 2021 Microsoft Corporation <paulmoore@microsoft.com>
# Author: Paul Moore <paul@paul-moore.com>
#

name: Setup the audit-testsuite
description: "Install CI dependencies for the audit-testsuite"
runs:
  using: "composite"
  steps:
  - run: sudo apt-get update
    shell: bash
  - run: sudo apt-get install -y build-essential gcc-multilib python3-pip file
    shell: bash
  - run: sudo apt-get install -y astyle
    shell: bash
  - run: sudo apt-get install -y liburing-dev
    shell: bash
  - run: sudo apt-get install -y perltidy
    shell: bash
  - run: sudo apt-get install -y python3-yapf
    shell: bash
