#!/bin/bash

# Detect OS distribution (Debian/Fedora/RHEL6/RHEL7).
distro=""

if [[ -r /etc/debian-version ]]; then
    distro="Debian"
elif [[ -r /etc/fedora-release ]]; then
    distro="Fedora"
elif [[ -r /etc/redhat-release ]]; then
    distro=$(sed -e 's/.*Linux[ \ta-zA-Z]*\([0-9]\+\).*/RHEL\1/' /etc/redhat-release)
fi

echo $distro
