#!/bin/sh

key=ghak8-setuid-exec
checkpoint=/tmp/audit_testsuite-syscall_execve_noBPRM_FCAPS-checkpoint

ausearch -ts recent --checkpoint $checkpoint
auditctl -a always,exit -F arch=b64 -S execve -C uid!=euid -F euid=0 -k $key

