#!/usr/bin/perl

use strict;
my $debug = 0;

use Test;
BEGIN { plan tests => 1 + 4 * 2 }

use File::Temp qw/ tempfile /;

my $basedir = $0;
$basedir =~ s|(.*)/[^/]*|$1|;

###
# functions

###
# setup

# reset audit
system("auditctl -D >& /dev/null");

# create stdout/stderr sinks
(my $fh_out, my $stdout) = tempfile(TEMPLATE => '/tmp/audit-testsuite-out-XXXX',
				    UNLINK => 1);
(my $fh_err, my $stderr) = tempfile(TEMPLATE => '/tmp/audit-testsuite-err-XXXX',
				    UNLINK => 1);

###
# tests
my @tests = (
	"ipv4_icmp",
	"ipv6_icmp",
	"ipv4_udp",
	"ipv6_udp",
);
my @proto = ( "", "6", "", "6");
my @chain = ( "INPUT", "INPUT", "INPUT", "INPUT");
my @param = (
	"-i lo -p icmp --icmp-type echo-request",
	"-i lo -p icmpv6 --icmpv6-type echo-request",
	"-i lo -p udp --dport 42424",
	"-i lo -p udp --dport 42424",
);
my @trig = (
	"ping -q -c 1 127.0.0.1 >/dev/null 2>&1",
	"ping -q -c 1 ::1 >/dev/null 2>&1",
	"exec 3<>/dev/udp/127.0.0.1/42424 >/dev/null 2>&1;echo hi >&3",
	"exec 4<>/dev/udp/::1/42424 >/dev/null 2>&1;echo hi >&4",
);
my @mark;
my @found;
my @fields;
for (0..$#tests) {
	$mark[$_] = sprintf("%x", int(rand(0xffffffff)));
	$found[$_] = 0;
	$fields[$_] = 0;
}
+my $fields = 5;

#
# set the iptables filters
for (0..$#tests) {
	system("ip" . $proto[$_] . "tables -I " . $chain[$_] . " "
		. $param[$_] . " -j AUDIT --type accept");
	system("ip" . $proto[$_] . "tables -I " . $chain[$_] . " -t mangle "
		. $param[$_] . " -j MARK --set-mark 0x" . $mark[$_]);
}
sleep 1;

# run the tests
for (0..$#tests) {
	system($trig[$_]);
}

system("sleep 1; sync");

# test if we generate any audit records from the filter rules
my $result = system("ausearch -i -m NETFILTER_PKT -ts recent > $stdout 2> $stderr");
ok($result, 0);

# test if we generate the NETFILTER_PKT records correctly
my $line;
while ($line = <$fh_out>) {
	for (0..$#tests) {
		if ($line =~ / mark=0x$mark[$_] /) {
			$found[$_] += 1;
			$fields[$_] += () = $line =~ / [^ =]*=[^ =]*/g;
		}
	}
}
for (0..$#tests) {
	ok($found[$_]); # Was the nfmarked parcket found?
}

for (0..$#tests) {
	ok($fields[$_] == $fields); # Correct number of fields?
}

###
# cleanup

for (0..$#tests) {
	system("ip" . $proto[$_] . "tables -D " . $chain[$_] . " "
		. $param[$_] . " -j AUDIT --type accept");
	system("ip" . $proto[$_] . "tables -D " . $chain[$_] . " -t mangle "
		. $param[$_] . " -j MARK --set-mark 0x" . $mark[$_]);
}
system("auditctl -D >& /dev/null");
