#!/usr/bin/perl

use strict;

use Test;
BEGIN { plan tests => 3 }

use File::Temp qw/ tempdir tempfile /;

my $basedir = $0;
$basedir =~ s|(.*)/[^/]*|$1|;

###
# functions

sub key_gen {
    my @chars = ( "A" .. "Z", "a" .. "z" );
    my $key   = "testsuite-" . time . "-";
    $key .= $chars[ rand @chars ] for 1 .. 8;
    return $key;
}

###
# setup

chomp( my $abi_bits = $ENV{MODE} != 0 ? $ENV{MODE} : `getconf LONG_BIT` );

# reset audit
system("auditctl -D >& /dev/null");

# create temp directory
my $dir = tempdir( TEMPLATE => '/tmp/audit-testsuite-XXXX', CLEANUP => 1 );

# create stdout/stderr sinks
( my $fh_out, my $stdout ) = tempfile(
    TEMPLATE => '/tmp/audit-testsuite-out-XXXX',
    UNLINK   => 1
);
( my $fh_err, my $stderr ) = tempfile(
    TEMPLATE => '/tmp/audit-testsuite-err-XXXX',
    UNLINK   => 1
);

###
# tests

my $nr_openat2 = 437;

# audit all open() syscalls on 64-bit systems
my $key = key_gen();
my $result;
my $result_open = system(
    "auditctl -a always,exit -F arch=b$abi_bits -S open -k $key 2> $stderr");
my $result_openat =
  system("auditctl -a always,exit -F arch=b$abi_bits -S openat -k $key");
my $result_openat2 =
  system("auditctl -a always,exit -F arch=b$abi_bits -S $nr_openat2 -k $key");
ok( $result_open == 0 or $result_openat == 0 or $result_openat2 == 0 );

# create a new file
( my $fh, my $filename ) =
  tempfile( TEMPLATE => $dir . "/file-XXXX", UNLINK => 1 );

system("$basedir/openat2 $dir file-openat2");
if ( defined $ENV{ATS_DEBUG} && $ENV{ATS_DEBUG} == 1 ) {
    system("echo Contents of $dir:;ls -ltr $dir");
}

# make sure the records had a chance to bubble through to the logs
system("auditctl -m syncmarker-$key");
for ( my $i = 0 ; $i < 10 ; $i++ ) {
    if (
        system("ausearch -m USER 2> /dev/null | grep -q syncmarker-$key") eq 0 )
    {
        last;
    }
    sleep(0.2);
}

# test if we generate any audit records
$result = system("ausearch -i -k $key > $stdout 2> $stderr");
ok( $result, 0 );

# test if we generate the SYSCALL record correctly
my $line;
my $found_syscall = 0;
my $found_parent  = 0;
my $found_create  = 0;
my $found_openat2 = 0;
while ( $line = <$fh_out> ) {
    if ( $line =~ /^type=SYSCALL /
        and ( $line =~ / syscall=open(at|at2)? / ) )
    {
        $found_syscall = 1;
    }
    if ( $line =~ /^type=OPENAT2 / ) {
        $found_openat2 = 1;
    }
}
ok(
    $found_syscall && ( ( $result_openat2 != 0 )
        || ( $result_openat2 == 0 && $found_openat2 == 1 ) )
);

###
# cleanup

system("auditctl -D >& /dev/null");

